name: Publish package

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  crates:
    if: github.repository == 'acristoffers/tree-sitter-matlab' && github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    uses: tree-sitter/workflows/.github/workflows/package-crates.yml@main
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
